#    cache: true
server:
  port: 80
  servlet:
    context-path: /hido

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    platform: mysql
    url: jdbc:mysql://localhost:3306/hospital?characterEncoding=utf-8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

    

